users:
- user_name: Alice
  datasets_list:
  - dataset_name: "IRIS"
    max_epsilon: 10
    max_delta: 0.0001
    current_epsilon: 1
    current_delta: 0.000001
  - dataset_name: "PENGUIN"
    max_epsilon: 5
    max_delta: 0.0005
    current_epsilon: 0.2
    current_delta: 0.0000001
- user_name: Bob
  datasets_list:
  - dataset_name: "IRIS"
    max_epsilon: 10
    max_delta: 0.0001
    current_epsilon: 0
    current_delta: 0
datasets: ["IRIS", "PENGUIN"]